# Installing packages
install.packages("devtools")
devtools::install_github("waldronlab/bugSigSimple")
#loading library
library (bugSigSimple)
dat <- readCurationSheet("/Users/ftzohra22/Desktop/School/Spring 2019/capstone/capstone analysis/Microbial signatures curation - signatures.tsv")
dim(dat)

#subsetting all signatures by curator
my.dat <- subsetByCurator(dat, curator="Fatima Zohra")
# all conditions curated by curator
table(my.dat[,"condition"])
#restricting data to certain conditions for analysis
ind <- my.dat[,"condition"] %in% c("chronic obstructive pulmonary disease", "gestational diabetes", "alzheimer's disease", "parkinson's disease", "stimulus or stress design")
my.dat2 <- my.dat[!ind,]
dim(my.dat2)

# list of conditions included in analysis 
table(my.dat2[,"condition"])

#overall frequencies of taxa in up and down
getMostFrequentTaxa(my.dat2, sig.type= "UP")
getMostFrequentTaxa(my.dat2, sig.type= "DOWN")

#subsetting by statistical test
subsetBystatisticaltest <- function(dat, statistical.test, statistical.test.column="statistical.test")
{
  ind <- dat[,statistical.test.column] == statistical.test
  return(dat[ind,])
}
table(my.dat2[,"statistical.test"])

#frequencies in LEfSe 
my.datalefse<- subsetBystatisticaltest(my.dat2,statistical.test= "LEfSe" )
dim (my.dataslefse)
getMostFrequentTaxa(my.datalefse, sig.type= "UP")
getMostFrequentTaxa(my.datalefse, sig.type= "DOWN")

#frequencies in Mann-Whitney
my.datamannwhitney<- subsetBystatisticaltest(my.dat2,statistical.test= "Mann-Whitney (Wilcoxon)" )
getMostFrequentTaxa(my.datamannwhitney, sig.type= "UP")
getMostFrequentTaxa(my.datamannwhitney, sig.type= "DOWN")

#frequencies in Kruskall-Wallis
my.datakruskal<- subsetBystatisticaltest(my.dat2,statistical.test= "Kruskall-Wallis" )
getMostFrequentTaxa(my.datakruskal, sig.type= "UP")
getMostFrequentTaxa(my.datakruskal, sig.type= "DOWN")

#frequencies in t-test
my.datattest<- subsetBystatisticaltest(my.dat2,statistical.test= "t-test" )
getMostFrequentTaxa(my.datattest, sig.type= "UP")
getMostFrequentTaxa(my.datattest, sig.type= "DOWN")

#common signatures in conditions
##restricting data to only UP

my.contrastsup <- c("UP")
ind1 <- my.dat2[,"UP.or.DOWN"] %in% my.contrastsup
my.dat3 <- my.dat2[ind1,]

  
extractSignatures(my.dat3)

my.sigs <- extractSignatures(my.dat3)
head (my.sigs)


cond.ext <- rep(my.dat3[,"condition"], lengths(my.sigs))
head(cond.ext)
table(cond.ext)

spl <- split(cond.ext, unlist(my.sigs))
head (spl)

ind <- order(lengths(spl), decreasing=TRUE)
head(spl[ind], n=15)

uspl <- lapply(spl, unique)
head(uspl[ind], n=15)

##restricting data to only DOWN rows
my.contrastsdown <- c("DOWN")
ind2 <- my.dat2[,"UP.or.DOWN"] %in% my.contrastsdown
my.dat4 <- my.dat2[ind2,]


extractSignatures(my.dat4)

my.sigs <- extractSignatures(my.dat4)
head (my.sigs)


cond.ext <- rep(my.dat4[,"condition"], lengths(my.sigs))
head(cond.ext)
table(cond.ext)

spl <- split(cond.ext, unlist(my.sigs))
head (spl)

ind <- order(lengths(spl), decreasing=TRUE)
head(spl[ind], n=15)

uspl <- lapply(spl, unique)
head(uspl[ind], n=15)






